---
title: "Team Project 1"
author: "Martin Ngoh"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(forecast)
library(grid)
library(Amelia)
library(tseries)
library(scales)
library(gridExtra)
library(lmtest)
library(lubridate)
library(zoo)
library(Rcpp)

knitr::opts_chunk$set(echo = TRUE)
```



# Read and understand data
``` {r, echo = FALSE}
liq = read.csv("C:/Users/Martin/OneDrive/Desktop/teamP1/usliquorsales.csv") 
liq <- liq[!apply(is.na(liq) | liq == "", 1, all),]

sum(is.na(liq))
sapply(liq, class)

liq$Period <- my(liq$Period)
liq$Value <- as.numeric(gsub(",","",liq$Value,fixed=TRUE))
sapply(liq, class)


```




#2. Plot monthly sales data

```{r, echo = FALSE}
ts_plot <- ggplot(liq, aes(Period,Value)) + geom_line(na.rm=TRUE) + 
  xlab("Month") + ylab("liq Sales in Millions") + 
  scale_x_date(labels = date_format(format= "%b-%Y"),breaks = date_breaks("5 year")) + 
  stat_smooth(colour = "green")

ts_plot
class(liq)

#Converting data into a time series object
liq_ts <-ts(liq[,c('Value')])
class(liq_ts)

#Plot time series with trend line
plot(liq_ts, col = "blue", main = "liq Sales Time Series Data")
abline(reg=lm(liq_ts~time(liq_ts)), col="lightgray") #plotting the trend line

#autocorrelation and Partial autocorrelation Plots
Acf(liq_ts)
Pacf(liq_ts)

#Lag plot of Data
gglagplot(liq_ts, set.lags=1:16)

Box.test(liq_ts, lag=24, fitdf=0, type="Lj")

###DECOMPOSING THE TIME SERIES (additive)
#Converting data into a time series object by year
liq_tsd <-ts(liq[,c('Value')], frequency=12)
class(liq_tsd)
component.ts = decompose(liq_tsd)
plot(component.ts)


liq_tsd %>%
  stl(t.window=24, s.window="periodic", robust=TRUE) %>%
  autoplot()

liq$c_value <-tsclean(liq_ts)

#Plot the cleaned data
c_ts_plot <- ggplot(liq, aes(Period,c_value)) + geom_line(na.rm=TRUE) + 
  xlab("Month") + ylab("liq Sales in Millions") + 
  scale_x_date(labels = date_format(format= "%b-%Y"),breaks = date_breaks("5 year")) + 
  stat_smooth(colour="green")
c_ts_plot

#Lets compare both cleaned and uncleaned plots
grid.arrange(ts_plot,c_ts_plot,ncol=1, top = textGrob("Uncleaned vs Cleaned Series"))

#Smoothing the time series and looking at the decomposed time series again
my_ts <- ts(na.omit(liq$c_value), frequency = 12)
plot(my_ts)

component.ts2 = decompose(my_ts)
plot(component.ts2)
```



#3.)  Naive Forecasting Method (for the next 24 months after observed data)
``` {r, echo = FALSE}
naive_forecast <-naive(liq_ts, 24)
summary(naive_forecast)
autoplot(naive_forecast)

#Check for fitted values and residuals
checkresiduals(naive_forecast)

```


#4.1) Smoothing the Series to uncover patterns in data
```{r, echo = FALSE}
#4.1 Moving Averages
#MA of order 5 (generally of odd numbers)
liq_ma<-ma(liq_ts, 5)
autoplot(liq_ts, series="Data") +
  autolayer(ma(liq_ts,5), series="5-MA") +
  xlab("Year") + ylab("Sales") +
  ggtitle("liq Sales Moving Average - 5 months") +
  scale_colour_manual(values=c("Data"="grey50","5-MA"="red"),
                      breaks=c("Data","5-MA"))
#MA of order 3
autoplot(liq_ts, series="Data") +
  autolayer(ma(liq_ts,3), series="3-MA") +
  xlab("Year") + ylab("Sales") +
  ggtitle("liq Sales Moving Average - 3 months") +
  scale_colour_manual(values=c("Data"="grey50","3-MA"="red"),
                      breaks=c("Data","3-MA"))

#MA of order 9
autoplot(liq_ts, series="Data") +
  autolayer(ma(liq_ts,9), series="9-MA") +
  xlab("Year") + ylab("Sales") +
  ggtitle("liq Sales Moving Average - 9 months") +
  scale_colour_manual(values=c("Data"="grey50","9-MA"="red"),
                      breaks=c("Data","9-MA"))

#Moving Average of Moving Averages (only for even order moving average to make them symmetric)
#A 2x4 moving average

autoplot(liq_ts, series = "Data") + 
  autolayer(ma(liq_ts, order = 4, centre = TRUE), series = "2x4-MA") +
  labs(x = "Year", y = "Sales") + 
  ggtitle("2x4 moving average of liqsales")

#Removing Seasonal effects (if it is there- say a 1 year seasonal variation)
autoplot(liq_ts, series = "Data") + 
  autolayer(ma(liq_ts, 12), series = "12-MA") +
  labs(x = "Year", y = "Sales") + 
  ggtitle("12-month moving average of liqsales") +
  scale_colour_manual(values=c("Data"="grey50","12-MA"="red"),
                      breaks=c("Data","12-MA"))
``` 



#5. Making the series stationary (identify level of differencing required) 
```{r, echo = FALSE}
adf.test(my_ts)
#To convert series to stationary, we need to know the level of differencing required
#Look at ACF (liqcorrelation plot for the series to identify the order of differencing required)
Acf(my_ts)
Pacf(my_ts)

```


#6. Forecasting with ARIMA Model
``` {r, echo = FALSE}
## 1 order differncing 

dfit1 <- arima(my_ts, order = c(0,1,0))
plot(residuals(dfit1))
Acf(residuals(dfit1))
Pacf(residuals(dfit1))

############################
dfit2 <- arima(my_ts, order =c(0,0,0), seasonal = list(order = c(0,1,0), period = 12))
plot(residuals(dfit2))
Acf(residuals(dfit2))
Pacf(residuals(dfit2))

#lets try and apply both seasonal and non-seasonal differencing, ARIMA(0,1,0)(0,1,0)[12]
dfit3 <- arima(my_ts, order =c(0,1,0), seasonal = list(order = c(0,1,0), period = 12))
plot(residuals(dfit3))
Acf(residuals(dfit3))
Pacf(residuals(dfit3))

#Since first ACF is -ve and most of the positive correlations are now negative (series is overdifferenced)
#we should add an MA term to the model but to know what order of MA we need,
#check the standard deviation of the models (sd=RMSE) 
summary(dfit1)
summary(dfit2)
summary(dfit3)

dfit4 <- arima(my_ts, order =c(0,1,1), seasonal = list(order = c(0,1,0), period = 12))
plot(residuals(dfit4))
Acf(residuals(dfit4))
Pacf(residuals(dfit4))

#Add a one-order MA component to the seasonal part and see what we get
dfit5 <- arima(my_ts, order =c(0,1,0), seasonal = list(order = c(0,1,1), period = 12))
plot(residuals(dfit5))
Acf(residuals(dfit5))
Pacf(residuals(dfit5))

#combine a MA component to non-seasonal and one to seasonal
dfit6 <- arima(my_ts, order =c(0,1,1), seasonal = list(order = c(0,1,1), period = 12))
plot(residuals(dfit6))
Acf(residuals(dfit6))
Pacf(residuals(dfit6))

#Pending statistically significant MA coefficient and low AIC the model seems a good fit
summary(dfit4)
summary(dfit5)
summary(dfit6)

#The coeftest() function in lmtest package can help us in getting the p-values of coefficients.
coeftest(dfit6)

#Check Minimum AIC and Iterate
dfit7 <- auto.arima(my_ts, seasonal = TRUE)
plot(residuals(dfit7))
Acf(residuals(dfit7))
Pacf(residuals(dfit7))

summary(dfit7)
coeftest(dfit7)
################

boxresult <- LjungBoxTest(dfit7$residuals, k=1, StartLag = 1)
boxresult
plot(boxresult[,3],main = "Ljung-Box Q Test",
     ylab = "P-values", xlabs = "Lag")


sum(table(unique(liq$Period)))

```

#7. Model Validation (n-fold holdout method)
```{r, echo = FALSE}
hold <- window(ts(my_ts), start =233)

#we will forecast data for the last two years (month = 233 to 256)
fit_predicted <- arima(ts(my_ts[-c(328:351)]), order =c(0,1,1), seasonal = list(order = c(0,1,2), period = 12))

forecast_pred <- forecast(fit_predicted,h=24)
plot(forecast_pred, main="")
lines(ts(my_ts))
```


#8. Forecasting
``` {r, echo = FALSE}
#Next step is to forecast the sales for another 24 months ahead of time. 
f_values <-forecast(dfit7, h=24)
plot(f_values, main="")

```
